---
eduid:
  worker:
    common:
      debug: yes
    ladok-x:
      api_server:
        host: :8080
    captcha:
      api_server:
        host: :8080
      production: false
      http_proxy: "some-proxy.se"
    x_service:
      api_server:
        host: 8080